version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: agile-accounting-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: agile_accounting
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - agile-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: agile-accounting-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@database:27017/agile_accounting?authSource=admin
      JWT_SECRET: 9f90c31f2f52be5ddce6043fb543321cad766c6eafa1ef949ace6299fca2c800382dbf3e45b22e81c13b83e2924b57a214bcafb94c60077b98125164548494b8
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - agile-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: agile-accounting-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - agile-network

volumes:
  mongodb_data:

networks:
  agile-network:
    driver: bridge